databases:
  - name: Recipe_app
    databaseName: postgresql
    user: postgresql

services:
  - type: web
    name: Recipe_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Recipe_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    isAllowList: []
    plan: free
    maxmemoryPolicy: noeviction