default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Recipe_App_development
  username: <%= ENV.fetch("DATABASE_USERNAME") {'postgres'} %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") {'Martial@5009'} %>

test:
  <<: *default
  database: Recipe_App_test

production:
  <<: *default
  database: Recipe_App_production
  username: Recipe_App
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
